const $=id=>document.getElementById(id), money=value=>`₹${Number(value).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
let analytics, selected;
function text(el,value){$(el).textContent=value}
function showError(message){$('notice').innerHTML=`<div class="notice">${message}</div>`}
async function api(path, options={}){const response=await fetch(path,options);const body=await response.json().catch(()=>({}));if(!response.ok)throw Error(body.detail||'Something went wrong. Please try again.');return body}
function bars(values, formatter=money){const max=Math.max(...Object.values(values));return Object.entries(values).map(([name,value])=>`<div class="bar"><span>${name}</span><span>${formatter(value)}</span><i style="--width:${value/max*100}%"></i></div>`).join('')}
async function loadDashboard(){try{analytics=await api('/analytics');text('revenue',money(analytics.total_revenue));text('transactions',analytics.total_transactions);text('units',analytics.total_items_sold);text('aov',money(analytics.average_transaction_value));text('best-product',analytics.best_product);text('best-category',analytics.best_category);text('best-product-evidence',`${analytics.best_product} generates ${money(analytics.product_revenue[analytics.best_product])}, the strongest product revenue.`);$('category-bars').innerHTML=bars(analytics.category_revenue);$('payment-mix').innerHTML=bars(analytics.payment_method_distribution,v=>`${v} transactions`)}catch(error){showError(`Unable to load merchant analytics. ${error.message}`)}}
function actionButton(opportunity){return `<button data-opportunity="${opportunity.opportunity_id}">Simulate & propose →</button>`}
async function loadOpportunities(){try{const data=await api('/ai/opportunities');selected=data.opportunities;$('opportunity-list').innerHTML=data.opportunities.map(item=>`<article class="opportunity"><span class="tag">${item.type}</span><h3>${item.title}</h3><p><b>Evidence:</b> ${item.evidence}</p><p>${item.recommendation}</p><p class="confidence">${item.confidence} confidence · ${item.risk_level} risk</p>${actionButton(item)}</article>`).join('');$('cross-sell').textContent=data.cross_sell_message||data.cross_sell.map(item=>`${item.product_a} + ${item.product_b}: ${item.reason}`).join(' ') }catch(error){$('opportunity-list').innerHTML=`<p class="loading">Unable to load opportunities. ${error.message}</p>`}}
function renderAdvice(item){$('advice').classList.remove('empty');$('advice').innerHTML=`<h3>${item.title}</h3><p>${item.recommendation}</p><div class="advice-grid"><div><small>Evidence</small><b>${item.evidence}</b></div><div><small>Goal</small><b>${item.expected_goal}</b></div><div><small>Risk</small><b>${item.risk_level}</b></div></div><button id="propose" >Simulate impact & propose action →</button>`;selected=[item]}
$('ask').onclick=async()=>{const question=$('question').value.trim();if(question.length<2)return showError('Please enter a question of at least two characters.');$('ask').disabled=true;try{renderAdvice(await api('/ai/advice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})}))}catch(error){showError(error.message)}finally{$('ask').disabled=false}};
document.addEventListener('click',async event=>{const id=event.target.dataset.opportunity;if(id){const item=selected.find(x=>x.opportunity_id===id);renderAdvice(item);$('copilot').scrollIntoView({behavior:'smooth'});return}if(event.target.id==='propose'){const item=selected[0];event.target.disabled=true;try{const action=await api('/agent/propose',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product:item.recommended_product,category:item.recommended_category,title:item.title,recommendation:item.recommendation,evidence:item.evidence})});$('advice').insertAdjacentHTML('beforeend',`<div class="sim"><b>Simulation / Estimate:</b> ${money(action.simulation.impact_low)}–${money(action.simulation.impact_high)} potential revenue impact.<br>${action.simulation.formula}</div><button data-approve="${action.action_id}">Approve this action</button>`);loadAudit()}catch(error){showError(error.message)}finally{event.target.disabled=false}}if(event.target.dataset.approve){event.target.disabled=true;try{const action=await api('/agent/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action_id:event.target.dataset.approve})});if(action.status==='AWAITING_PAYMENT')openCheckout(action);else showError(action.failure_reason||'The action could not be executed.');loadAudit()}catch(error){showError(error.message);event.target.disabled=false}}});
function openCheckout(action){if(!window.Razorpay)return showError('Razorpay Checkout could not be loaded.');new Razorpay({key:action.razorpay_key_id,amount:action.razorpay_amount,currency:action.razorpay_currency,name:'RazorGrow AI',description:'Test Mode — no real money charged',order_id:action.razorpay_order_id,handler:async payment=>{try{await api('/agent/payment/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payment)});loadAudit();$('advice').insertAdjacentHTML('beforeend','<p><b>✓ Payment verified server-side. The action is recorded in the audit trail.</b></p>')}catch(error){showError(error.message)}}}).open()}
async function loadAudit(){try{const status=$('status-filter').value;const data=await api(`/agent/audit${status?`?status=${encodeURIComponent(status)}`:''}`);$('audit').innerHTML=data.actions.length?data.actions.map(a=>`<article class="audit-item"><div><h3>${a.title||a.type}</h3><p>${a.product||'—'} · ${a.category||'—'} · ${new Date(a.created_at).toLocaleString()}</p><p>${a.message}</p>${a.failure_reason?`<p>${a.failure_reason}</p>`:''}</div><span class="badge ${a.status}">${a.status.replaceAll('_',' ')}</span></article>`).join(''):'<p class="loading">No growth actions match this filter.</p>'}catch(error){$('audit').innerHTML=`<p class="loading">Unable to load audit trail. ${error.message}</p>`}}
$('refresh').onclick=()=>Promise.all([loadDashboard(),loadOpportunities(),loadAudit()]);$('status-filter').onchange=loadAudit;Promise.all([loadDashboard(),loadOpportunities(),loadAudit()]);
